version: '3.4'

services:
  db:
    image: ronaldosr/mysql-curso:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "rest_spring_boot"
    ports:
      - "3308:3306"
    volumes:
      - ./18SpringBootSuporteDocker:/18SpringBootSuporteDocker
      - ~/.m2:/root/.m2
    networks:
      - ronaldo-network
  springboot-curso:
    image: ronaldosr/springboot-curso
    restart: always
    build: ./18SpringBootSuporteDocker
    working_dir: /18SpringBootSuporteDocker
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./18SpringBootSuporteDocker:/18SpringBootSuporteDocker
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - ronaldo-network 
networks:
    ronaldo-network:
        driver: bridge