DROP TABLE IF EXISTS livro;

CREATE TABLE IF NOT EXISTS livro (
	id bigint generated BY DEFAULT AS identity,
	autor VARCHAR(180) NOT NULL,
	data_publicacao DATE NOT NULL,
	preco DECIMAL(19, 2) NOT NULL,
	titulo VARCHAR(250) NOT NULL,
	PRIMARY KEY(id)
);