insert into livro (autor, data_publicacao, preco, titulo) values ('Mario Roome', '1959-02-13', '191.02', 'eu massa donec dapibus duis at velit eu');
insert into livro (autor, data_publicacao, preco, titulo) values ('Brian Shenton', '2003-04-30', '194.79', 'integer ac neque duis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Benjamin Chamberlayne', '2010-11-23', '103.90', 'luctus tincidunt nulla mollis molestie lorem quisque');
insert into livro (autor, data_publicacao, preco, titulo) values ('Feliza West-Frimley', '2003-05-02', '104.08', 'nascetur ridiculus mus etiam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Bradford Rowlinson', '1981-10-17', '52.48', 'neque aenean auctor gravida');
insert into livro (autor, data_publicacao, preco, titulo) values ('Spike O'' Connell', '1974-06-21', '172.43', 'amet consectetuer adipiscing');
insert into livro (autor, data_publicacao, preco, titulo) values ('Sheelah Blackaby', '2014-07-22', '147.21', 'ut blandit non interdum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Thadeus Shreeve', '2014-02-23', '107.86', 'eu est congue elementum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Hamel Causby', '1983-12-12', '32.23', 'rutrum rutrum neque aenean auctor gravida sem');
insert into livro (autor, data_publicacao, preco, titulo) values ('Tedda Arnefield', '1956-02-06', '183.36', 'in hac habitasse platea dictumst');
insert into livro (autor, data_publicacao, preco, titulo) values ('Nanete Priel', '1995-11-22', '40.04', 'faucibus orci luctus et ultrices posuere');
insert into livro (autor, data_publicacao, preco, titulo) values ('Whitney Burkill', '1980-08-10', '70.26', 'vivamus vestibulum sagittis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Tabitha Mayberry', '1978-07-12', '73.75', 'montes nascetur ridiculus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Leif Elcock', '1963-07-30', '114.18', 'elementum in hac habitasse platea dictumst morbi');
insert into livro (autor, data_publicacao, preco, titulo) values ('Simonette Regenhardt', '1971-05-09', '103.83', 'in quam fringilla rhoncus mauris enim leo');
insert into livro (autor, data_publicacao, preco, titulo) values ('Griffy Mailes', '1973-07-05', '122.22', 'in consequat ut nulla sed');
insert into livro (autor, data_publicacao, preco, titulo) values ('Celinda Godmer', '2005-07-19', '149.92', 'at nunc commodo placerat praesent blandit nam nulla');
insert into livro (autor, data_publicacao, preco, titulo) values ('Orin Flux', '2009-07-01', '13.64', 'at nibh in hac habitasse platea');
insert into livro (autor, data_publicacao, preco, titulo) values ('Babette Retchford', '2004-01-17', '190.31', 'erat eros viverra');
insert into livro (autor, data_publicacao, preco, titulo) values ('Cinnamon McCleary', '2010-06-16', '131.97', 'nulla suspendisse potenti cras in purus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Bendite Hallmark', '2014-12-20', '162.77', 'orci luctus et');
insert into livro (autor, data_publicacao, preco, titulo) values ('Allis Paute', '1994-12-29', '75.56', 'quis augue luctus tincidunt');
insert into livro (autor, data_publicacao, preco, titulo) values ('Shirlene Sanders', '1960-01-13', '169.56', 'nunc nisl duis bibendum felis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Nikolaus Belhomme', '1965-05-24', '173.37', 'consequat varius integer ac leo pellentesque ultrices');
insert into livro (autor, data_publicacao, preco, titulo) values ('Hadlee Dissman', '2013-09-26', '77.76', 'nibh in quis justo maecenas rhoncus aliquam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Codi Spiring', '1979-01-29', '116.45', 'varius ut blandit non');
insert into livro (autor, data_publicacao, preco, titulo) values ('Katharina McRamsey', '1961-04-24', '189.43', 'interdum eu tincidunt');
insert into livro (autor, data_publicacao, preco, titulo) values ('Elaina Cayette', '2007-02-13', '54.22', 'diam id ornare imperdiet');
insert into livro (autor, data_publicacao, preco, titulo) values ('Christabella McDonogh', '1966-01-31', '59.14', 'et tempus semper est quam pharetra magna');
insert into livro (autor, data_publicacao, preco, titulo) values ('Nanci McKenzie', '2012-11-01', '36.43', 'turpis donec posuere metus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Elysia Deamer', '2005-02-26', '194.94', 'elit sodales scelerisque mauris sit amet');
insert into livro (autor, data_publicacao, preco, titulo) values ('Merill Jain', '1982-12-18', '83.20', 'sed accumsan felis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Kylila Aven', '1950-08-13', '115.45', 'tellus semper interdum mauris ullamcorper');
insert into livro (autor, data_publicacao, preco, titulo) values ('Meridel Hargrave', '1955-01-18', '153.97', 'mauris vulputate elementum nullam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Brianna Worley', '1989-05-09', '133.03', 'erat quisque erat');
insert into livro (autor, data_publicacao, preco, titulo) values ('Pansy Sivior', '1955-11-25', '66.78', 'varius ut blandit non interdum in ante vestibulum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Angelico Wyldish', '2008-10-14', '139.99', 'proin leo odio');
insert into livro (autor, data_publicacao, preco, titulo) values ('Elspeth Nesterov', '1993-12-30', '79.46', 'placerat ante nulla justo aliquam quis turpis eget');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jaquith Kinnock', '1999-07-01', '178.94', 'orci nullam molestie');
insert into livro (autor, data_publicacao, preco, titulo) values ('Caty Shotton', '1978-07-03', '166.70', 'vestibulum ante ipsum primis in faucibus orci luctus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Petr Sketh', '1977-03-16', '175.20', 'justo in blandit ultrices');
insert into livro (autor, data_publicacao, preco, titulo) values ('Alia Cochern', '1998-07-24', '160.45', 'dapibus at diam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Vaclav Gelletly', '1984-09-22', '158.07', 'lacus morbi quis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Frederik Ablewhite', '1980-06-02', '82.29', 'sit amet sem fusce consequat nulla');
insert into livro (autor, data_publicacao, preco, titulo) values ('Carly Scates', '2016-07-28', '84.03', 'sed sagittis nam congue risus semper porta');
insert into livro (autor, data_publicacao, preco, titulo) values ('Fairlie Jonah', '1950-12-13', '198.33', 'porttitor lorem id ligula suspendisse');
insert into livro (autor, data_publicacao, preco, titulo) values ('Iosep Drohun', '1985-03-07', '178.94', 'proin interdum mauris non ligula pellentesque');
insert into livro (autor, data_publicacao, preco, titulo) values ('Daisi Mosley', '1976-07-12', '40.98', 'est risus auctor sed tristique in');
insert into livro (autor, data_publicacao, preco, titulo) values ('Roobbie Baudry', '2018-03-05', '181.16', 'in hac habitasse platea dictumst');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lilyan Sangster', '1993-08-01', '22.36', 'duis faucibus accumsan odio curabitur convallis duis consequat');
insert into livro (autor, data_publicacao, preco, titulo) values ('Mel Dimelow', '1997-06-08', '197.05', 'ut at dolor quis odio consequat');
insert into livro (autor, data_publicacao, preco, titulo) values ('Harv Norman', '2012-09-23', '63.11', 'quisque arcu libero rutrum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Renaud MacCarter', '1960-02-10', '38.40', 'mattis odio donec vitae nisi');
insert into livro (autor, data_publicacao, preco, titulo) values ('Mace Pieters', '2015-05-11', '80.61', 'magna at nunc commodo placerat praesent blandit nam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Chester Cardero', '1995-12-01', '150.25', 'mattis odio donec vitae nisi nam ultrices libero');
insert into livro (autor, data_publicacao, preco, titulo) values ('Kare Penwright', '1954-02-20', '78.59', 'morbi ut odio cras');
insert into livro (autor, data_publicacao, preco, titulo) values ('Agathe Evins', '1969-12-15', '187.41', 'vulputate luctus cum sociis natoque');
insert into livro (autor, data_publicacao, preco, titulo) values ('Evelina Coyte', '2014-07-29', '106.38', 'ipsum primis in faucibus orci luctus et ultrices');
insert into livro (autor, data_publicacao, preco, titulo) values ('Faustine Brodhead', '1992-01-03', '183.09', 'sit amet justo morbi');
insert into livro (autor, data_publicacao, preco, titulo) values ('Gustavus Bellino', '1989-07-22', '23.96', 'maecenas leo odio condimentum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Micah Osbaldstone', '1995-06-23', '155.74', 'a ipsum integer a nibh');
insert into livro (autor, data_publicacao, preco, titulo) values ('Johanna Drabble', '1966-12-01', '138.25', 'pede venenatis non');
insert into livro (autor, data_publicacao, preco, titulo) values ('Giulietta Hindenburg', '1966-10-23', '77.47', 'augue quam sollicitudin vitae consectetuer eget rutrum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ola Wackett', '1995-05-27', '168.82', 'magna bibendum imperdiet');
insert into livro (autor, data_publicacao, preco, titulo) values ('Dunc Culy', '1961-05-03', '115.61', 'erat nulla tempus vivamus in felis eu');
insert into livro (autor, data_publicacao, preco, titulo) values ('Base Hanaford', '1982-09-03', '173.89', 'tristique fusce congue diam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Sven Edge', '2013-06-21', '39.83', 'viverra dapibus nulla suscipit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Marijn Quantrill', '2005-10-20', '69.78', 'libero ut massa volutpat convallis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jewell MacVay', '1982-08-03', '153.56', 'vestibulum aliquet ultrices erat tortor sollicitudin');
insert into livro (autor, data_publicacao, preco, titulo) values ('Linc Brosoli', '2010-02-25', '15.83', 'sed ante vivamus tortor duis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Granger Darch', '2002-12-02', '180.28', 'bibendum felis sed interdum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Evin Sadd', '2015-12-15', '160.30', 'rutrum ac lobortis vel');
insert into livro (autor, data_publicacao, preco, titulo) values ('Gates Philpin', '1959-03-19', '30.69', 'in sapien iaculis congue');
insert into livro (autor, data_publicacao, preco, titulo) values ('Othelia Di Biasio', '1980-10-26', '84.31', 'a suscipit nulla elit ac');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jenine Patesel', '1968-01-24', '34.16', 'commodo placerat praesent blandit nam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Kermit Stempe', '1990-12-15', '41.45', 'ante vivamus tortor duis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Pris Ambrose', '1976-05-20', '153.12', 'pulvinar sed nisl nunc');
insert into livro (autor, data_publicacao, preco, titulo) values ('Will Halliwell', '1985-06-17', '62.73', 'lobortis convallis tortor risus dapibus augue vel accumsan');
insert into livro (autor, data_publicacao, preco, titulo) values ('Margi Jochens', '2002-05-02', '74.08', 'eget tempus vel pede morbi porttitor');
insert into livro (autor, data_publicacao, preco, titulo) values ('Seamus Gowthorpe', '1979-11-08', '31.35', 'dictumst etiam faucibus cursus urna ut tellus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Kelsy Sheivels', '1974-08-21', '40.62', 'ipsum ac tellus semper interdum mauris ullamcorper purus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Doll Maxfield', '1966-11-27', '35.52', 'mi pede malesuada in imperdiet');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ches De Blase', '1996-04-04', '163.49', 'pellentesque viverra pede ac diam cras');
insert into livro (autor, data_publicacao, preco, titulo) values ('Eolande Traylen', '1966-07-10', '94.61', 'mauris vulputate elementum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Berny Josskoviz', '1959-10-31', '155.83', 'etiam faucibus cursus urna ut tellus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Libbie Casburn', '1984-05-06', '46.37', 'accumsan felis ut at dolor');
insert into livro (autor, data_publicacao, preco, titulo) values ('Marie-jeanne Mulryan', '1950-02-27', '141.87', 'vulputate elementum nullam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Barbabra Fantonetti', '1976-12-04', '110.50', 'ut mauris eget');
insert into livro (autor, data_publicacao, preco, titulo) values ('Elbert Havick', '1997-11-02', '155.35', 'nulla neque libero convallis eget eleifend');
insert into livro (autor, data_publicacao, preco, titulo) values ('Fanechka Yeates', '1964-01-27', '117.05', 'pharetra magna ac consequat metus sapien ut');
insert into livro (autor, data_publicacao, preco, titulo) values ('Nehemiah Batram', '2013-08-31', '199.60', 'in magna bibendum imperdiet');
insert into livro (autor, data_publicacao, preco, titulo) values ('Puff Gornall', '1952-02-03', '59.07', 'at ipsum ac tellus semper interdum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Sheeree Lawrinson', '1954-05-19', '63.24', 'blandit nam nulla integer pede');
insert into livro (autor, data_publicacao, preco, titulo) values ('Daryl Francois', '1963-11-26', '76.83', 'turpis adipiscing lorem');
insert into livro (autor, data_publicacao, preco, titulo) values ('Carrol Duthie', '1968-12-09', '160.54', 'bibendum morbi non quam nec');
insert into livro (autor, data_publicacao, preco, titulo) values ('Clark Phizackarley', '2007-06-12', '193.33', 'nec dui luctus rutrum nulla tellus in sagittis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Nollie Galilee', '1985-07-07', '126.21', 'nam nulla integer pede');
insert into livro (autor, data_publicacao, preco, titulo) values ('Abramo Dodman', '2001-10-09', '78.76', 'imperdiet et commodo vulputate justo in blandit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Annnora Eccleston', '1997-04-20', '56.07', 'sit amet cursus id turpis integer aliquet massa');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jandy Fairbrace', '1955-05-24', '17.91', 'nulla quisque arcu libero rutrum ac lobortis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Kalina Gobell', '1962-04-12', '12.55', 'at feugiat non pretium');
insert into livro (autor, data_publicacao, preco, titulo) values ('Claudio Droghan', '1974-11-14', '20.23', 'morbi non quam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lemmie Feavearyear', '1959-01-07', '58.97', 'lorem ipsum dolor sit amet');
insert into livro (autor, data_publicacao, preco, titulo) values ('Clerkclaude Ilchuk', '2013-09-13', '48.47', 'cras pellentesque volutpat dui');
insert into livro (autor, data_publicacao, preco, titulo) values ('Holli Folkerts', '2013-06-17', '167.69', 'tristique fusce congue diam id ornare imperdiet sapien');
insert into livro (autor, data_publicacao, preco, titulo) values ('Eirena Heelis', '1980-04-14', '158.46', 'nunc nisl duis bibendum felis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Gun Lumox', '1978-07-13', '108.15', 'cras in purus eu magna vulputate luctus cum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Deni Freda', '1975-06-24', '139.04', 'sed lacus morbi sem mauris laoreet ut');
insert into livro (autor, data_publicacao, preco, titulo) values ('Kellina Riding', '1991-01-14', '13.97', 'curabitur in libero ut massa volutpat');
insert into livro (autor, data_publicacao, preco, titulo) values ('Cecile Morrieson', '2005-11-06', '154.79', 'ultrices posuere cubilia');
insert into livro (autor, data_publicacao, preco, titulo) values ('Zollie McAteer', '1972-10-15', '86.33', 'orci vehicula condimentum curabitur in libero ut massa');
insert into livro (autor, data_publicacao, preco, titulo) values ('Donall Hallgarth', '1972-01-05', '45.95', 'ut dolor morbi vel lectus in quam fringilla');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lina Howel', '1968-08-22', '52.40', 'enim leo rhoncus sed vestibulum sit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Vasily Silver', '1996-04-04', '169.18', 'risus praesent lectus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ade Hellin', '1987-02-09', '108.68', 'lorem vitae mattis nibh ligula nec sem duis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Tansy Kitchingham', '1952-08-08', '178.68', 'quisque ut erat curabitur gravida nisi at nibh');
insert into livro (autor, data_publicacao, preco, titulo) values ('Rena Brecknell', '1953-07-02', '116.67', 'et tempus semper est');
insert into livro (autor, data_publicacao, preco, titulo) values ('Brandy Skinner', '2015-07-28', '58.28', 'eget tincidunt eget');
insert into livro (autor, data_publicacao, preco, titulo) values ('Megan Gillatt', '1994-08-31', '52.30', 'amet erat nulla tempus vivamus in felis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Kristin Hollows', '1999-03-10', '31.81', 'congue vivamus metus arcu adipiscing');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lucian Phelips', '1976-08-26', '61.12', 'nisi nam ultrices libero non mattis pulvinar nulla');
insert into livro (autor, data_publicacao, preco, titulo) values ('Mab Lintot', '1974-12-06', '160.76', 'viverra pede ac diam cras pellentesque volutpat');
insert into livro (autor, data_publicacao, preco, titulo) values ('Hugo Grattage', '1955-09-10', '196.45', 'in lectus pellentesque at nulla suspendisse potenti cras');
insert into livro (autor, data_publicacao, preco, titulo) values ('Max Trimme', '1973-05-19', '15.93', 'nulla suscipit ligula in');
insert into livro (autor, data_publicacao, preco, titulo) values ('Aurora Pedrazzi', '1977-02-25', '170.25', 'amet sapien dignissim vestibulum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Dorrie Kleinfeld', '1999-12-11', '173.67', 'augue quam sollicitudin vitae consectetuer eget');
insert into livro (autor, data_publicacao, preco, titulo) values ('Allyn Whitby', '1989-02-20', '18.70', 'elit ac nulla sed vel');
insert into livro (autor, data_publicacao, preco, titulo) values ('Kelly Cronkshaw', '2003-10-22', '148.81', 'non mauris morbi non lectus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Barri Beere', '2004-12-26', '62.52', 'in ante vestibulum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Wolfgang Brunner', '1970-04-14', '197.91', 'integer a nibh in quis justo maecenas rhoncus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Allx Clewes', '2003-10-11', '25.06', 'mus etiam vel');
insert into livro (autor, data_publicacao, preco, titulo) values ('Baxter Hayball', '1998-07-17', '33.66', 'dolor vel est donec odio justo');
insert into livro (autor, data_publicacao, preco, titulo) values ('Aurel O''Kinedy', '1997-05-29', '111.53', 'in quis justo');
insert into livro (autor, data_publicacao, preco, titulo) values ('Evie Vickerstaff', '1962-07-19', '152.44', 'in hac habitasse platea');
insert into livro (autor, data_publicacao, preco, titulo) values ('Analiese Redford', '1972-03-12', '32.72', 'eget massa tempor convallis nulla neque');
insert into livro (autor, data_publicacao, preco, titulo) values ('Layton Chastang', '2008-05-29', '81.58', 'nibh in lectus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Saree Manicomb', '1956-03-27', '194.29', 'rutrum at lorem integer tincidunt ante');
insert into livro (autor, data_publicacao, preco, titulo) values ('Sari Cases', '1989-12-11', '178.50', 'donec quis orci eget orci vehicula condimentum curabitur');
insert into livro (autor, data_publicacao, preco, titulo) values ('Teodor Cardenas', '1999-06-02', '113.02', 'tempus sit amet sem');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jeremiah Denison', '2003-03-25', '18.99', 'sit amet turpis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Maxi Toppin', '1988-05-11', '91.98', 'nisi at nibh in');
insert into livro (autor, data_publicacao, preco, titulo) values ('Dorey Nussgen', '2004-10-18', '113.24', 'molestie hendrerit at');
insert into livro (autor, data_publicacao, preco, titulo) values ('Fidelia O''Doireidh', '1959-10-05', '142.72', 'leo odio condimentum id luctus nec');
insert into livro (autor, data_publicacao, preco, titulo) values ('Raf Szymanowicz', '2015-05-05', '160.77', 'sit amet consectetuer adipiscing');
insert into livro (autor, data_publicacao, preco, titulo) values ('Dix Elix', '1955-07-12', '133.33', 'sociis natoque penatibus et magnis dis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Thorstein Zannetti', '1978-03-22', '34.52', 'cubilia curae duis faucibus accumsan odio');
insert into livro (autor, data_publicacao, preco, titulo) values ('Constantia Burridge', '1983-06-07', '178.97', 'varius nulla facilisi cras');
insert into livro (autor, data_publicacao, preco, titulo) values ('Dian Reston', '1995-09-16', '162.42', 'quisque erat eros viverra eget congue eget');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lorin Tomini', '1958-07-19', '138.91', 'pretium iaculis diam erat');
insert into livro (autor, data_publicacao, preco, titulo) values ('Alla Silveston', '2004-11-10', '188.68', 'sapien sapien non mi');
insert into livro (autor, data_publicacao, preco, titulo) values ('Thatcher Stolli', '1998-01-09', '187.90', 'mauris viverra diam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lolly Rooper', '1992-09-18', '190.39', 'faucibus accumsan odio curabitur convallis duis consequat');
insert into livro (autor, data_publicacao, preco, titulo) values ('Nomi Linney', '2013-08-24', '81.07', 'justo maecenas rhoncus aliquam lacus morbi');
insert into livro (autor, data_publicacao, preco, titulo) values ('Maris Winckworth', '1997-07-03', '173.92', 'ultricies eu nibh quisque id');
insert into livro (autor, data_publicacao, preco, titulo) values ('April Kuna', '1975-10-10', '92.56', 'scelerisque quam turpis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Alfreda Mannock', '1983-11-04', '178.49', 'ipsum primis in faucibus orci');
insert into livro (autor, data_publicacao, preco, titulo) values ('Barri Bene', '1966-11-18', '177.70', 'duis bibendum morbi non quam nec dui');
insert into livro (autor, data_publicacao, preco, titulo) values ('Guillemette Heckner', '2005-04-29', '55.59', 'dictumst aliquam augue quam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Carmelle Sappy', '1976-12-18', '60.54', 'elementum nullam varius nulla facilisi');
insert into livro (autor, data_publicacao, preco, titulo) values ('Bartram Eayrs', '2008-07-20', '83.90', 'dictumst aliquam augue');
insert into livro (autor, data_publicacao, preco, titulo) values ('Keefe Carpenter', '2009-12-13', '11.59', 'pretium iaculis diam erat');
insert into livro (autor, data_publicacao, preco, titulo) values ('Zola Gledhall', '2007-10-14', '31.95', 'nulla suspendisse potenti cras');
insert into livro (autor, data_publicacao, preco, titulo) values ('Charita Nisby', '2016-04-09', '164.30', 'a libero nam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Edlin Urling', '1981-06-29', '21.59', 'sapien sapien non mi integer ac neque duis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ilse Napolione', '1984-07-14', '16.32', 'sed sagittis nam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Adriane Quare', '1966-12-08', '18.40', 'ac neque duis bibendum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Nestor Hamon', '1966-11-24', '102.44', 'leo odio porttitor');
insert into livro (autor, data_publicacao, preco, titulo) values ('Paula Edmenson', '1997-06-26', '146.24', 'etiam faucibus cursus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Merla Biset', '1964-06-22', '182.96', 'volutpat dui maecenas tristique est et tempus semper');
insert into livro (autor, data_publicacao, preco, titulo) values ('Prinz Alekseev', '2008-12-21', '90.81', 'nulla suspendisse potenti cras in purus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Matteo Storrs', '1980-05-09', '170.86', 'amet cursus id turpis integer');
insert into livro (autor, data_publicacao, preco, titulo) values ('Garrot Delafont', '1964-03-12', '67.09', 'vel pede morbi porttitor lorem id');
insert into livro (autor, data_publicacao, preco, titulo) values ('Kai Spradbery', '1983-10-30', '154.38', 'ipsum aliquam non mauris');
insert into livro (autor, data_publicacao, preco, titulo) values ('Gothart Willcott', '1983-10-04', '189.75', 'integer aliquet massa id');
insert into livro (autor, data_publicacao, preco, titulo) values ('Elenore Vittori', '2000-04-15', '20.76', 'aliquet ultrices erat tortor sollicitudin mi');
insert into livro (autor, data_publicacao, preco, titulo) values ('Rana Boyes', '2015-04-17', '182.50', 'pede justo eu');
insert into livro (autor, data_publicacao, preco, titulo) values ('Tildy Aylesbury', '1962-10-21', '33.13', 'blandit mi in porttitor pede');
insert into livro (autor, data_publicacao, preco, titulo) values ('Myriam Greenhalgh', '1976-04-05', '44.23', 'cursus vestibulum proin eu');
insert into livro (autor, data_publicacao, preco, titulo) values ('Harper Polon', '2018-11-15', '27.53', 'est congue elementum in hac habitasse');
insert into livro (autor, data_publicacao, preco, titulo) values ('Odey Svanini', '1981-11-14', '170.17', 'pede ullamcorper augue');
insert into livro (autor, data_publicacao, preco, titulo) values ('Sherman Hackworth', '1973-08-11', '186.63', 'ac consequat metus sapien ut nunc vestibulum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Drusie Cardew', '1951-05-31', '13.08', 'nullam orci pede venenatis non sodales');
insert into livro (autor, data_publicacao, preco, titulo) values ('Tracey Doogue', '1969-05-27', '10.45', 'magna vestibulum aliquet ultrices erat tortor');
insert into livro (autor, data_publicacao, preco, titulo) values ('Gilbertine Nolda', '2000-12-15', '44.04', 'ornare consequat lectus in');
insert into livro (autor, data_publicacao, preco, titulo) values ('Twila Riteley', '1995-05-17', '181.47', 'cras mi pede malesuada in imperdiet et commodo');
insert into livro (autor, data_publicacao, preco, titulo) values ('Gus Goseling', '2009-12-04', '167.89', 'in tempus sit amet sem fusce');
insert into livro (autor, data_publicacao, preco, titulo) values ('Rowan Clipsham', '1975-03-19', '45.05', 'eu sapien cursus vestibulum proin eu mi');
insert into livro (autor, data_publicacao, preco, titulo) values ('Gabie Magner', '2007-10-21', '195.69', 'leo odio porttitor id consequat in consequat');
insert into livro (autor, data_publicacao, preco, titulo) values ('Mellie Brach', '1958-12-03', '176.47', 'mattis pulvinar nulla pede ullamcorper augue a suscipit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ron Conisbee', '2018-01-15', '39.84', 'auctor gravida sem praesent id');
insert into livro (autor, data_publicacao, preco, titulo) values ('Louis Edgecumbe', '1992-10-25', '15.10', 'lacinia eget tincidunt eget tempus vel');
insert into livro (autor, data_publicacao, preco, titulo) values ('Tobe Houten', '2007-03-13', '124.67', 'fusce lacus purus aliquet at feugiat non');
insert into livro (autor, data_publicacao, preco, titulo) values ('Sherlocke Huegett', '1987-02-04', '102.70', 'eu mi nulla ac enim in');
insert into livro (autor, data_publicacao, preco, titulo) values ('Stanleigh Pickford', '1971-10-04', '159.94', 'cras mi pede malesuada in');
insert into livro (autor, data_publicacao, preco, titulo) values ('Raychel Caplan', '1988-05-24', '14.76', 'vel nulla eget');
insert into livro (autor, data_publicacao, preco, titulo) values ('Rolland Lobb', '1954-08-02', '87.62', 'in libero ut massa volutpat convallis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Olenolin Nelson', '1960-02-23', '44.34', 'tristique est et tempus semper est quam pharetra');
insert into livro (autor, data_publicacao, preco, titulo) values ('Page Jaquet', '2018-08-10', '12.86', 'ac neque duis bibendum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ulrike Ebbers', '1976-06-01', '127.99', 'nascetur ridiculus mus vivamus vestibulum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Paton Dominicacci', '1982-10-30', '91.34', 'libero nullam sit amet turpis elementum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Sullivan Cheshir', '1982-03-25', '146.22', 'habitasse platea dictumst morbi vestibulum velit id');
insert into livro (autor, data_publicacao, preco, titulo) values ('Reinhold Jayme', '1986-03-14', '66.97', 'turpis integer aliquet massa id lobortis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Henri Keywood', '1988-12-26', '134.07', 'sapien ut nunc vestibulum ante');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jervis Trythall', '2014-04-29', '121.83', 'rutrum neque aenean auctor gravida sem praesent id');
insert into livro (autor, data_publicacao, preco, titulo) values ('Reginauld Marcos', '1992-11-17', '161.66', 'proin leo odio porttitor id consequat');
insert into livro (autor, data_publicacao, preco, titulo) values ('Agnella Younger', '1972-05-22', '181.51', 'porttitor pede justo eu massa donec dapibus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lorant Patriskson', '1958-07-14', '162.30', 'ut massa quis augue luctus tincidunt nulla');
insert into livro (autor, data_publicacao, preco, titulo) values ('Nedi Hakking', '1970-10-05', '177.87', 'justo lacinia eget tincidunt eget');
insert into livro (autor, data_publicacao, preco, titulo) values ('Cara Stegers', '1958-10-03', '160.74', 'risus auctor sed tristique');
insert into livro (autor, data_publicacao, preco, titulo) values ('Laurel Marmon', '2006-07-26', '188.71', 'quam fringilla rhoncus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Kittie Bockmaster', '1971-07-22', '115.02', 'pede justo lacinia eget');
insert into livro (autor, data_publicacao, preco, titulo) values ('Rozella Shapiro', '2000-08-16', '17.04', 'dictumst aliquam augue quam sollicitudin vitae');
insert into livro (autor, data_publicacao, preco, titulo) values ('Humberto Maskrey', '1983-01-09', '179.42', 'felis ut at dolor quis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Aloisia Ocklin', '2018-07-05', '95.93', 'nunc commodo placerat praesent blandit nam nulla');
insert into livro (autor, data_publicacao, preco, titulo) values ('Romonda Stapylton', '1971-11-09', '115.53', 'ipsum dolor sit amet');
insert into livro (autor, data_publicacao, preco, titulo) values ('Myrvyn Shreeves', '2015-05-04', '158.39', 'quam a odio in hac habitasse platea dictumst');
insert into livro (autor, data_publicacao, preco, titulo) values ('Nomi Cattemull', '2010-04-21', '115.52', 'aenean fermentum donec ut mauris eget massa');
insert into livro (autor, data_publicacao, preco, titulo) values ('Tine Antic', '1963-01-07', '14.43', 'ac diam cras pellentesque volutpat dui maecenas');
insert into livro (autor, data_publicacao, preco, titulo) values ('Dacy Gerriets', '1970-03-02', '131.54', 'eu orci mauris lacinia sapien quis libero nullam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Constancy Jendrich', '1993-11-21', '58.13', 'leo rhoncus sed vestibulum sit amet cursus id');
insert into livro (autor, data_publicacao, preco, titulo) values ('Noreen Ruby', '1954-05-15', '171.80', 'interdum mauris non ligula pellentesque ultrices phasellus id');
insert into livro (autor, data_publicacao, preco, titulo) values ('Livvy Dougher', '1996-11-08', '95.53', 'nibh in lectus pellentesque at nulla');
insert into livro (autor, data_publicacao, preco, titulo) values ('Gordon Flay', '1971-06-01', '162.83', 'penatibus et magnis dis parturient montes');
insert into livro (autor, data_publicacao, preco, titulo) values ('Madelle Lavigne', '1961-12-16', '97.18', 'pellentesque at nulla suspendisse potenti cras in purus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Carmelle Hynd', '1979-09-11', '116.42', 'sed nisl nunc rhoncus dui');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jesselyn Gudge', '2018-08-08', '163.26', 'hac habitasse platea dictumst maecenas ut massa');
insert into livro (autor, data_publicacao, preco, titulo) values ('Alana Mathwen', '1966-06-01', '141.16', 'pretium iaculis diam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Johna Awton', '2014-08-01', '13.45', 'ipsum primis in');
insert into livro (autor, data_publicacao, preco, titulo) values ('Maxie Woodman', '1955-05-13', '20.07', 'a ipsum integer');
insert into livro (autor, data_publicacao, preco, titulo) values ('Kaila Abbe', '2001-09-22', '103.87', 'sapien cursus vestibulum proin eu mi nulla ac');
insert into livro (autor, data_publicacao, preco, titulo) values ('Sharity Bonsale', '2016-01-06', '189.90', 'hac habitasse platea dictumst morbi');
insert into livro (autor, data_publicacao, preco, titulo) values ('Loren Rodger', '1986-03-22', '140.15', 'orci pede venenatis non');
insert into livro (autor, data_publicacao, preco, titulo) values ('Winn Isakovitch', '1970-11-08', '64.34', 'ut volutpat sapien arcu sed augue aliquam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Bari Wrixon', '2015-05-31', '106.59', 'elit sodales scelerisque');
insert into livro (autor, data_publicacao, preco, titulo) values ('Everard Tunny', '1982-06-10', '62.86', 'mattis nibh ligula nec sem');
insert into livro (autor, data_publicacao, preco, titulo) values ('Regan Franciottoi', '1998-01-23', '125.15', 'dapibus at diam nam tristique');
insert into livro (autor, data_publicacao, preco, titulo) values ('Sybil Gradley', '2008-04-20', '105.22', 'sapien cursus vestibulum proin eu mi');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jeni Pawel', '1974-07-10', '60.59', 'orci luctus et ultrices posuere');
insert into livro (autor, data_publicacao, preco, titulo) values ('Durward Meni', '1981-04-24', '192.17', 'massa donec dapibus duis at velit eu est');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ellen MacDirmid', '1978-05-30', '46.90', 'venenatis tristique fusce congue diam id ornare');
insert into livro (autor, data_publicacao, preco, titulo) values ('Walsh Brookesbie', '1977-10-25', '27.78', 'cursus urna ut');
insert into livro (autor, data_publicacao, preco, titulo) values ('Edgardo Kemston', '1958-03-28', '143.75', 'purus phasellus in felis donec');
insert into livro (autor, data_publicacao, preco, titulo) values ('Chris Ilyinski', '1951-08-04', '199.54', 'curae nulla dapibus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Colline Stanislaw', '2009-12-24', '91.23', 'sit amet erat nulla');
insert into livro (autor, data_publicacao, preco, titulo) values ('Danica Minards', '1982-09-05', '43.95', 'eget congue eget semper');
insert into livro (autor, data_publicacao, preco, titulo) values ('Yvon Gors', '1977-09-28', '153.29', 'ultrices phasellus id sapien');
insert into livro (autor, data_publicacao, preco, titulo) values ('Loni Aldham', '1970-09-04', '116.18', 'metus vitae ipsum aliquam non');
insert into livro (autor, data_publicacao, preco, titulo) values ('Adele Breckwell', '1972-10-31', '48.12', 'orci eget orci vehicula condimentum curabitur');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jonah Batcheldor', '2012-05-21', '197.18', 'ac diam cras pellentesque');
insert into livro (autor, data_publicacao, preco, titulo) values ('Sydney Bauldrey', '1996-11-18', '76.96', 'mus vivamus vestibulum sagittis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Margret Danielsen', '1978-05-18', '28.77', 'mauris laoreet ut');
insert into livro (autor, data_publicacao, preco, titulo) values ('Yoshiko Fyall', '1998-11-25', '35.84', 'etiam pretium iaculis justo');
insert into livro (autor, data_publicacao, preco, titulo) values ('Chris Brindley', '1979-04-27', '188.39', 'lacus at velit vivamus vel');
insert into livro (autor, data_publicacao, preco, titulo) values ('Loreen Colyer', '1955-10-27', '191.63', 'leo odio porttitor id consequat in consequat');
insert into livro (autor, data_publicacao, preco, titulo) values ('Sigfried Alders', '2004-01-24', '32.91', 'sit amet sapien dignissim vestibulum vestibulum ante ipsum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Gustave Tomsa', '1969-12-25', '86.41', 'est lacinia nisi venenatis tristique');
insert into livro (autor, data_publicacao, preco, titulo) values ('Evangelin Letten', '2005-08-06', '160.14', 'id massa id nisl');
insert into livro (autor, data_publicacao, preco, titulo) values ('Haskell Rammell', '1980-03-13', '38.25', 'orci mauris lacinia');
insert into livro (autor, data_publicacao, preco, titulo) values ('Avictor Thaim', '1969-08-27', '46.07', 'ut volutpat sapien arcu sed augue aliquam erat');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lavena MacSkeagan', '1998-03-05', '39.43', 'nulla facilisi cras');
insert into livro (autor, data_publicacao, preco, titulo) values ('Francoise Scannell', '2007-08-01', '191.44', 'posuere cubilia curae duis faucibus accumsan odio');
insert into livro (autor, data_publicacao, preco, titulo) values ('Franzen MacRinn', '1983-12-12', '133.24', 'posuere metus vitae ipsum aliquam non mauris');
insert into livro (autor, data_publicacao, preco, titulo) values ('Adelheid Iverson', '1978-02-21', '100.59', 'rutrum rutrum neque aenean auctor gravida');
insert into livro (autor, data_publicacao, preco, titulo) values ('Gabi Brazur', '1971-11-21', '167.52', 'venenatis lacinia aenean sit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Fraze Ide', '1968-07-27', '106.99', 'ac est lacinia nisi venenatis tristique fusce');
insert into livro (autor, data_publicacao, preco, titulo) values ('Hyacintha Blackaller', '2010-10-14', '144.96', 'libero convallis eget eleifend luctus ultricies eu');
insert into livro (autor, data_publicacao, preco, titulo) values ('Guinna Vernall', '1975-11-25', '93.51', 'ut dolor morbi vel lectus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Dwain Willimott', '1968-01-08', '80.82', 'amet nunc viverra dapibus nulla suscipit ligula');
insert into livro (autor, data_publicacao, preco, titulo) values ('Moll Hosby', '1958-02-18', '132.57', 'nisi venenatis tristique fusce');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lavinia Basilio', '1962-06-13', '94.13', 'in consequat ut nulla sed accumsan felis ut');
insert into livro (autor, data_publicacao, preco, titulo) values ('Appolonia Reavell', '1992-05-17', '73.31', 'congue elementum in');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ezra Brogan', '2017-03-18', '163.26', 'turpis donec posuere metus vitae ipsum aliquam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Carrissa Surplice', '1988-03-23', '65.89', 'curabitur in libero ut massa');
insert into livro (autor, data_publicacao, preco, titulo) values ('Hilliard Mitham', '1981-01-09', '154.10', 'metus sapien ut nunc vestibulum ante ipsum primis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Laurent Blackett', '1955-11-16', '27.85', 'est risus auctor sed tristique in tempus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Alexandrina Ingerfield', '1972-07-18', '197.65', 'mi nulla ac enim in tempor');
insert into livro (autor, data_publicacao, preco, titulo) values ('Beckie Mussolini', '2002-05-26', '156.11', 'vivamus vel nulla eget');
insert into livro (autor, data_publicacao, preco, titulo) values ('Tabina Tatford', '1965-05-14', '18.88', 'nisi venenatis tristique fusce congue diam id ornare');
insert into livro (autor, data_publicacao, preco, titulo) values ('Talya Moorcraft', '1963-01-07', '42.88', 'dolor sit amet consectetuer adipiscing elit proin');
insert into livro (autor, data_publicacao, preco, titulo) values ('Dodi Bouller', '2007-04-07', '196.11', 'orci nullam molestie nibh in lectus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jayson Woliter', '1992-09-10', '25.34', 'vel nulla eget');
insert into livro (autor, data_publicacao, preco, titulo) values ('Atlanta Sewley', '1957-10-17', '49.23', 'nibh quisque id justo sit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Romola Gleeson', '1999-02-08', '109.07', 'auctor sed tristique');
insert into livro (autor, data_publicacao, preco, titulo) values ('Bail Mayne', '1983-04-22', '174.73', 'dis parturient montes nascetur ridiculus mus vivamus vestibulum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Odie Seyfart', '1982-11-04', '28.06', 'pretium quis lectus suspendisse');
insert into livro (autor, data_publicacao, preco, titulo) values ('Sheree Reisenstein', '1966-07-21', '175.36', 'sagittis sapien cum sociis natoque penatibus et magnis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Raynell McAllen', '2018-10-31', '97.14', 'odio justo sollicitudin');
insert into livro (autor, data_publicacao, preco, titulo) values ('Colman Ughini', '1976-06-26', '87.76', 'at turpis donec posuere metus vitae ipsum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Hagan Langley', '1961-08-08', '131.49', 'pellentesque eget nunc');
insert into livro (autor, data_publicacao, preco, titulo) values ('Shaine Gumley', '1973-06-22', '48.11', 'duis consequat dui nec nisi');
insert into livro (autor, data_publicacao, preco, titulo) values ('Magdaia Sharland', '1978-08-24', '139.14', 'at velit vivamus vel');
insert into livro (autor, data_publicacao, preco, titulo) values ('Enrico Basso', '2013-04-12', '54.84', 'vel est donec odio');
insert into livro (autor, data_publicacao, preco, titulo) values ('Mickey Dionisetti', '1982-06-05', '111.65', 'id luctus nec');
insert into livro (autor, data_publicacao, preco, titulo) values ('My Teece', '1969-06-12', '190.24', 'libero nam dui proin leo');
insert into livro (autor, data_publicacao, preco, titulo) values ('Kary Simanek', '1994-09-20', '120.90', 'eget tincidunt eget tempus vel pede morbi porttitor');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jacobo Shawl', '2007-09-09', '198.97', 'sollicitudin vitae consectetuer eget rutrum at lorem integer');
insert into livro (autor, data_publicacao, preco, titulo) values ('Natalina Akister', '2005-07-10', '172.69', 'nulla sed vel enim sit amet nunc viverra');
insert into livro (autor, data_publicacao, preco, titulo) values ('Dareen Fine', '1983-05-07', '131.04', 'dui nec nisi volutpat eleifend donec ut');
insert into livro (autor, data_publicacao, preco, titulo) values ('Mariquilla Walsh', '1964-03-14', '148.48', 'nibh ligula nec sem duis aliquam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Cordelie Kaasman', '1952-05-14', '111.36', 'at lorem integer tincidunt ante vel ipsum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Alexandr Harlett', '1993-12-19', '138.06', 'proin at turpis a');
insert into livro (autor, data_publicacao, preco, titulo) values ('Monika Tieman', '1951-12-24', '152.51', 'penatibus et magnis dis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Emmaline Andrews', '1981-12-28', '89.23', 'mauris non ligula');
insert into livro (autor, data_publicacao, preco, titulo) values ('Gibb McJerrow', '2004-09-07', '132.16', 'urna pretium nisl ut volutpat sapien arcu');
insert into livro (autor, data_publicacao, preco, titulo) values ('Addison Jedrzejkiewicz', '2000-03-17', '28.68', 'duis consequat dui nec nisi');
insert into livro (autor, data_publicacao, preco, titulo) values ('Thor Fidgett', '1982-08-13', '194.62', 'eu mi nulla ac enim in');
insert into livro (autor, data_publicacao, preco, titulo) values ('Caron Hinzer', '1963-01-10', '113.70', 'ridiculus mus etiam vel augue vestibulum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Dorothee Cuningham', '2016-04-15', '12.65', 'nunc rhoncus dui vel sem sed sagittis nam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Kinny Hollingby', '1985-06-08', '189.41', 'nullam orci pede venenatis non sodales sed');
insert into livro (autor, data_publicacao, preco, titulo) values ('Bondy Sowte', '2017-06-25', '145.07', 'ipsum primis in faucibus orci');
insert into livro (autor, data_publicacao, preco, titulo) values ('Phylis Durrant', '1977-08-01', '96.97', 'molestie lorem quisque ut erat curabitur');
insert into livro (autor, data_publicacao, preco, titulo) values ('Phillip Tregidgo', '1962-01-12', '78.38', 'sagittis sapien cum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Anni Condy', '2004-05-30', '14.56', 'amet lobortis sapien sapien non');
insert into livro (autor, data_publicacao, preco, titulo) values ('Solomon Semiraz', '1993-10-27', '12.43', 'tempor turpis nec euismod scelerisque quam turpis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Janifer Klageman', '1989-10-10', '50.14', 'massa volutpat convallis morbi odio odio');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jessalyn Vautrey', '1960-12-15', '94.24', 'pede libero quis orci nullam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Roshelle Grzegorecki', '2001-07-26', '184.22', 'felis sed lacus morbi sem');
insert into livro (autor, data_publicacao, preco, titulo) values ('Modesta Cochet', '2015-04-16', '184.09', 'arcu sed augue aliquam erat volutpat in congue');
insert into livro (autor, data_publicacao, preco, titulo) values ('Paulie Edwicke', '1996-06-17', '158.74', 'diam cras pellentesque volutpat dui maecenas tristique');
insert into livro (autor, data_publicacao, preco, titulo) values ('Carmelina Menci', '2017-08-20', '147.73', 'varius ut blandit non interdum in ante vestibulum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Nadeen Dengate', '1985-03-26', '160.28', 'quis tortor id nulla ultrices');
insert into livro (autor, data_publicacao, preco, titulo) values ('Arda Oldroyd', '2007-03-30', '117.32', 'primis in faucibus orci luctus et ultrices posuere');
insert into livro (autor, data_publicacao, preco, titulo) values ('Britta Ellerton', '2004-06-18', '133.30', 'ut suscipit a feugiat et eros vestibulum ac');
insert into livro (autor, data_publicacao, preco, titulo) values ('Darbie Mixon', '1991-11-18', '28.79', 'ultrices posuere cubilia curae duis faucibus accumsan');
insert into livro (autor, data_publicacao, preco, titulo) values ('Veronike Snasel', '1990-01-02', '25.36', 'aliquam erat volutpat in congue etiam justo etiam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Bryanty Vanner', '1957-06-22', '192.77', 'sapien urna pretium nisl ut');
insert into livro (autor, data_publicacao, preco, titulo) values ('Enoch Marlen', '1956-04-08', '65.24', 'turpis eget elit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ignacius Dobson', '1955-01-26', '155.60', 'odio justo sollicitudin ut suscipit a feugiat et');
insert into livro (autor, data_publicacao, preco, titulo) values ('Shannon Dwelley', '1969-08-21', '72.95', 'luctus tincidunt nulla mollis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Joellyn Nurny', '1980-03-08', '192.72', 'mauris eget massa tempor convallis nulla neque');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lorianna Timoney', '2000-05-22', '116.04', 'ut suscipit a feugiat et eros vestibulum ac');
insert into livro (autor, data_publicacao, preco, titulo) values ('Cobbie Cherry', '2006-02-19', '58.06', 'dolor sit amet consectetuer adipiscing');
insert into livro (autor, data_publicacao, preco, titulo) values ('Robinia Scotney', '1999-12-14', '167.20', 'integer ac leo pellentesque ultrices');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lucian Cawte', '1958-05-03', '39.33', 'faucibus orci luctus et ultrices posuere cubilia');
insert into livro (autor, data_publicacao, preco, titulo) values ('Reggy Caulton', '1996-05-14', '179.79', 'adipiscing molestie hendrerit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lindsy Woolfoot', '1999-12-05', '156.11', 'duis bibendum felis sed interdum venenatis turpis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Mel Toothill', '2015-06-10', '29.76', 'magna ac consequat metus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Sean Khoter', '1983-08-04', '63.96', 'malesuada in imperdiet et commodo');
insert into livro (autor, data_publicacao, preco, titulo) values ('Marlie Redmile', '1963-11-08', '106.88', 'aenean auctor gravida sem');
insert into livro (autor, data_publicacao, preco, titulo) values ('Gipsy Yurenev', '1996-04-09', '67.14', 'vestibulum ante ipsum primis in faucibus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Raquel Troubridge', '1950-10-02', '82.80', 'sit amet nunc viverra dapibus nulla suscipit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ive Blaze', '2009-06-02', '118.08', 'nunc vestibulum ante ipsum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Natala Kalker', '2009-03-20', '55.50', 'lorem ipsum dolor sit amet consectetuer adipiscing elit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Roderich Balsellie', '1973-09-02', '106.43', 'lacus purus aliquet');
insert into livro (autor, data_publicacao, preco, titulo) values ('Gaultiero Pitkeathley', '1984-08-23', '17.35', 'posuere cubilia curae nulla dapibus dolor');
insert into livro (autor, data_publicacao, preco, titulo) values ('Dyanne Chandlar', '1971-04-19', '61.66', 'dui proin leo odio porttitor id');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ericka Strathman', '2009-09-07', '57.86', 'feugiat non pretium quis lectus suspendisse');
insert into livro (autor, data_publicacao, preco, titulo) values ('Nollie Dryden', '1958-02-11', '88.37', 'congue diam id ornare imperdiet sapien');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ward Van T''Hoog', '2004-10-05', '28.86', 'amet erat nulla tempus vivamus in');
insert into livro (autor, data_publicacao, preco, titulo) values ('Launce Orsay', '2013-08-20', '132.72', 'et commodo vulputate justo in blandit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Alberto Bointon', '2002-07-07', '31.71', 'id lobortis convallis tortor');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jenifer Selly', '1995-05-26', '18.43', 'sit amet sapien');
insert into livro (autor, data_publicacao, preco, titulo) values ('Hy Burehill', '1988-09-19', '34.91', 'convallis duis consequat');
insert into livro (autor, data_publicacao, preco, titulo) values ('Emalee Cambridge', '2018-10-09', '166.50', 'suspendisse accumsan tortor quis turpis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ken Blowers', '1981-09-09', '196.76', 'quam nec dui luctus rutrum nulla');
insert into livro (autor, data_publicacao, preco, titulo) values ('Haskel German', '1990-05-17', '151.57', 'leo pellentesque ultrices mattis odio donec');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ozzy Petyakov', '2018-04-23', '187.83', 'luctus ultricies eu nibh quisque id justo');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ilyssa Giraudoux', '1981-02-06', '55.85', 'fusce congue diam id ornare imperdiet sapien urna');
insert into livro (autor, data_publicacao, preco, titulo) values ('Karon Pioch', '1956-04-13', '44.60', 'ante vel ipsum praesent blandit lacinia');
insert into livro (autor, data_publicacao, preco, titulo) values ('Marilyn Grube', '1983-09-09', '52.12', 'ac lobortis vel dapibus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Chiarra Wortley', '2018-04-28', '24.65', 'et ultrices posuere cubilia curae');
insert into livro (autor, data_publicacao, preco, titulo) values ('Sherwynd Congram', '1955-04-15', '164.84', 'odio consequat varius integer');
insert into livro (autor, data_publicacao, preco, titulo) values ('Nicky Semble', '2010-10-28', '73.50', 'proin leo odio');
insert into livro (autor, data_publicacao, preco, titulo) values ('Cherey Trenholme', '1985-01-31', '115.31', 'bibendum imperdiet nullam orci pede venenatis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Baily Cordner', '1953-08-01', '163.59', 'lectus pellentesque at nulla suspendisse');
insert into livro (autor, data_publicacao, preco, titulo) values ('Mikael Lippatt', '1982-04-19', '106.78', 'odio consequat varius integer ac leo');
insert into livro (autor, data_publicacao, preco, titulo) values ('Patsy Klugman', '1993-05-03', '33.64', 'morbi porttitor lorem id');
insert into livro (autor, data_publicacao, preco, titulo) values ('Dex Andrioni', '1985-03-21', '158.22', 'nulla eget eros elementum');
insert into livro (autor, data_publicacao, preco, titulo) values ('My Ezele', '1959-06-22', '11.95', 'est et tempus semper est quam pharetra magna');
insert into livro (autor, data_publicacao, preco, titulo) values ('Marlo Windress', '1978-02-18', '24.79', 'quam sapien varius ut blandit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Aymer Standrin', '1962-11-05', '83.62', 'consequat in consequat ut');
insert into livro (autor, data_publicacao, preco, titulo) values ('Miriam Signore', '2013-07-20', '143.04', 'non mauris morbi non lectus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Marney Gowlett', '2015-07-26', '111.26', 'risus dapibus augue vel accumsan tellus nisi');
insert into livro (autor, data_publicacao, preco, titulo) values ('Crystal Fiveash', '1986-12-09', '108.02', 'ultrices enim lorem ipsum dolor sit amet');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jordan Bottrell', '1950-07-16', '151.68', 'turpis elementum ligula vehicula consequat morbi a ipsum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Alan Malling', '2008-05-08', '199.12', 'nulla mollis molestie lorem quisque ut');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ashli Ibeson', '1968-09-11', '75.74', 'id luctus nec molestie sed justo');
insert into livro (autor, data_publicacao, preco, titulo) values ('Dael Matthisson', '1980-09-02', '165.22', 'congue elementum in');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ivory Grabiec', '1993-09-24', '88.39', 'massa id lobortis convallis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Michele Hulme', '1992-11-24', '47.00', 'eros vestibulum ac est lacinia nisi venenatis tristique');
insert into livro (autor, data_publicacao, preco, titulo) values ('Winnie Skokoe', '1962-06-08', '85.41', 'morbi non quam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jacquelin Castro', '2016-07-04', '190.08', 'massa tempor convallis nulla neque');
insert into livro (autor, data_publicacao, preco, titulo) values ('Bobbye Turfs', '2011-11-03', '107.12', 'volutpat convallis morbi odio');
insert into livro (autor, data_publicacao, preco, titulo) values ('Earvin Balls', '2012-01-13', '78.05', 'pretium iaculis diam erat fermentum justo nec');
insert into livro (autor, data_publicacao, preco, titulo) values ('Roselin Cruz', '2018-08-30', '172.39', 'ac nulla sed');
insert into livro (autor, data_publicacao, preco, titulo) values ('Yard Braden', '1954-09-13', '126.45', 'nascetur ridiculus mus vivamus vestibulum sagittis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Abbey Karpenya', '1993-09-21', '100.25', 'pede justo eu massa donec dapibus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Alanson Turgoose', '1984-12-01', '119.88', 'sem duis aliquam convallis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Cecil Oaten', '2012-05-09', '121.55', 'praesent id massa id nisl');
insert into livro (autor, data_publicacao, preco, titulo) values ('Cassie Karlqvist', '1955-11-20', '28.59', 'enim lorem ipsum dolor sit amet');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lolly Havelin', '2010-01-16', '198.58', 'enim leo rhoncus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Cassandry Fernyhough', '2010-03-04', '144.73', 'sed accumsan felis ut at');
insert into livro (autor, data_publicacao, preco, titulo) values ('Essie Norvell', '1970-03-11', '193.97', 'libero nam dui proin leo odio porttitor id');
insert into livro (autor, data_publicacao, preco, titulo) values ('Gussie Kyston', '1968-01-22', '119.10', 'hac habitasse platea dictumst maecenas ut');
insert into livro (autor, data_publicacao, preco, titulo) values ('Herve Porson', '2007-02-14', '69.99', 'sodales sed tincidunt eu felis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lauretta Sproston', '1951-07-08', '56.02', 'feugiat non pretium quis lectus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Durant Pieracci', '2009-11-01', '41.60', 'duis ac nibh fusce lacus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Forest Haygreen', '1982-08-01', '92.48', 'tristique est et tempus semper est quam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ryun Helstrom', '2006-05-13', '152.29', 'pulvinar sed nisl');
insert into livro (autor, data_publicacao, preco, titulo) values ('Shandee Sedgeman', '1995-01-11', '124.14', 'vehicula condimentum curabitur');
insert into livro (autor, data_publicacao, preco, titulo) values ('Adelaida Cardoso', '1975-09-14', '46.68', 'sociis natoque penatibus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Evelina Gartery', '1991-01-28', '184.77', 'vitae consectetuer eget rutrum at');
insert into livro (autor, data_publicacao, preco, titulo) values ('Bastien Winchurch', '1952-04-12', '84.86', 'et ultrices posuere');
insert into livro (autor, data_publicacao, preco, titulo) values ('Chloris Sill', '1951-04-03', '104.21', 'sed nisl nunc');
insert into livro (autor, data_publicacao, preco, titulo) values ('Connie Ruberry', '1979-05-10', '38.89', 'leo rhoncus sed vestibulum sit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Cristionna Stears', '1958-12-03', '178.77', 'varius nulla facilisi cras non velit nec');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lura Filipychev', '1988-12-22', '196.75', 'amet eros suspendisse accumsan tortor quis turpis sed');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ailina Spykings', '1976-09-05', '27.86', 'integer aliquet massa id lobortis convallis tortor risus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Edyth Scotchbrook', '1971-07-19', '189.78', 'vestibulum eget vulputate ut ultrices vel');
insert into livro (autor, data_publicacao, preco, titulo) values ('Damaris Ilsley', '1983-09-24', '144.00', 'suspendisse potenti nullam porttitor lacus at turpis donec');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lynnea Beidebeke', '1972-08-17', '171.15', 'ultrices posuere cubilia curae mauris viverra diam vitae');
insert into livro (autor, data_publicacao, preco, titulo) values ('Janene Godbold', '1977-04-16', '183.04', 'ante ipsum primis in faucibus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Delcina Claringbold', '2007-02-25', '75.65', 'magna bibendum imperdiet');
insert into livro (autor, data_publicacao, preco, titulo) values ('Wolf Wackley', '1989-11-21', '43.50', 'ut massa quis augue luctus tincidunt nulla mollis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Franz Lailey', '1992-07-07', '150.38', 'sapien non mi integer');
insert into livro (autor, data_publicacao, preco, titulo) values ('Petr Antonellini', '1965-11-15', '129.42', 'adipiscing molestie hendrerit at vulputate vitae nisl aenean');
insert into livro (autor, data_publicacao, preco, titulo) values ('Louis Guilayn', '1994-05-23', '50.85', 'neque duis bibendum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Clarey Regi', '1950-08-05', '187.92', 'et magnis dis parturient montes nascetur ridiculus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jemimah Leidl', '1954-08-09', '25.76', 'ut at dolor');
insert into livro (autor, data_publicacao, preco, titulo) values ('Corina Union', '2011-12-19', '87.18', 'facilisi cras non velit nec');
insert into livro (autor, data_publicacao, preco, titulo) values ('Leigh Grelik', '1952-06-23', '60.79', 'convallis eget eleifend luctus ultricies eu nibh quisque');
insert into livro (autor, data_publicacao, preco, titulo) values ('Brander Rembrandt', '1953-08-01', '161.50', 'phasellus in felis donec semper sapien a');
insert into livro (autor, data_publicacao, preco, titulo) values ('Oralla MacTerrelly', '1971-10-06', '164.36', 'lectus aliquam sit amet');
insert into livro (autor, data_publicacao, preco, titulo) values ('Hal Crossland', '1959-06-30', '72.76', 'dolor sit amet consectetuer adipiscing');
insert into livro (autor, data_publicacao, preco, titulo) values ('Theodora Ridpath', '1955-07-10', '39.82', 'vel enim sit amet nunc viverra');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ardis Patton', '1997-10-09', '115.38', 'nibh ligula nec sem duis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Everett Molnar', '1973-09-08', '11.07', 'mattis pulvinar nulla pede ullamcorper augue a suscipit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Edik Pardue', '1955-01-27', '119.08', 'quam turpis adipiscing lorem vitae mattis nibh');
insert into livro (autor, data_publicacao, preco, titulo) values ('Rickert Jimes', '1989-02-16', '173.00', 'rhoncus dui vel sem sed sagittis nam congue');
insert into livro (autor, data_publicacao, preco, titulo) values ('Pedro Kmiec', '1955-12-13', '165.82', 'sollicitudin vitae consectetuer eget rutrum at');
insert into livro (autor, data_publicacao, preco, titulo) values ('Carey Muttock', '1997-03-02', '30.49', 'sem praesent id massa');
insert into livro (autor, data_publicacao, preco, titulo) values ('Malvin McCrow', '1958-01-03', '127.92', 'congue eget semper rutrum nulla nunc purus phasellus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Arch Canland', '1957-03-16', '91.08', 'suspendisse accumsan tortor quis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Mag Tanzer', '1996-06-25', '37.81', 'orci pede venenatis non');
insert into livro (autor, data_publicacao, preco, titulo) values ('Drusie Rappport', '1963-10-26', '144.62', 'bibendum morbi non quam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Julius Velten', '2001-01-29', '116.79', 'sagittis sapien cum sociis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ansel Batistelli', '1976-05-14', '116.95', 'eget vulputate ut ultrices vel augue vestibulum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Margeaux Grabham', '1977-04-20', '68.99', 'donec dapibus duis at velit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Pren Itzkovitch', '2010-09-05', '29.17', 'nulla tellus in sagittis dui');
insert into livro (autor, data_publicacao, preco, titulo) values ('Steffane Hampe', '1987-09-13', '54.21', 'quis lectus suspendisse potenti in');
insert into livro (autor, data_publicacao, preco, titulo) values ('Christina Rockcliffe', '1991-02-27', '83.75', 'nulla ultrices aliquet maecenas leo odio condimentum id');
insert into livro (autor, data_publicacao, preco, titulo) values ('Dolley Chstney', '2007-01-28', '35.30', 'vulputate luctus cum sociis natoque');
insert into livro (autor, data_publicacao, preco, titulo) values ('Gerald Corkel', '1972-10-14', '150.08', 'rutrum rutrum neque aenean auctor gravida sem');
insert into livro (autor, data_publicacao, preco, titulo) values ('Bogey Golt', '1986-08-07', '166.17', 'lorem ipsum dolor sit amet');
insert into livro (autor, data_publicacao, preco, titulo) values ('Gaylor Blockwell', '1952-06-25', '185.60', 'vel accumsan tellus nisi eu orci mauris lacinia');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lavinia Weldrake', '1969-08-19', '153.28', 'arcu adipiscing molestie hendrerit at vulputate vitae');
insert into livro (autor, data_publicacao, preco, titulo) values ('Phaidra Garmanson', '1964-03-22', '73.90', 'sociis natoque penatibus et magnis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Teddie Joskovitch', '1985-01-03', '57.62', 'lacinia aenean sit amet');
insert into livro (autor, data_publicacao, preco, titulo) values ('Arron Gateshill', '1971-09-14', '117.10', 'id mauris vulputate elementum nullam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Buddie Upson', '1975-12-16', '73.78', 'semper sapien a libero nam dui');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lanni Dumbar', '1963-02-22', '108.82', 'donec posuere metus vitae ipsum aliquam non mauris');
insert into livro (autor, data_publicacao, preco, titulo) values ('Klement Pedrick', '2001-03-24', '35.51', 'eros suspendisse accumsan tortor quis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Mavis Plinck', '2015-12-28', '161.60', 'auctor gravida sem praesent');
insert into livro (autor, data_publicacao, preco, titulo) values ('Colver Benley', '1992-02-18', '13.84', 'libero quis orci nullam molestie');
insert into livro (autor, data_publicacao, preco, titulo) values ('Randolph Moukes', '1971-01-01', '47.15', 'dolor quis odio');
insert into livro (autor, data_publicacao, preco, titulo) values ('Constancia Van den Oord', '1995-10-13', '42.90', 'ac diam cras');
insert into livro (autor, data_publicacao, preco, titulo) values ('Dani Crufts', '1982-01-10', '187.00', 'blandit non interdum in ante vestibulum ante');
insert into livro (autor, data_publicacao, preco, titulo) values ('Karil Macguire', '1968-07-11', '70.02', 'hac habitasse platea dictumst morbi vestibulum velit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Mandie Leggis', '1980-02-10', '110.16', 'felis donec semper sapien a libero nam dui');
insert into livro (autor, data_publicacao, preco, titulo) values ('Tomasine Biffin', '2017-01-24', '172.14', 'non mauris morbi');
insert into livro (autor, data_publicacao, preco, titulo) values ('Rubin Undy', '1972-05-08', '31.75', 'tincidunt lacus at velit vivamus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Augustus Derwin', '1974-05-15', '147.86', 'sollicitudin mi sit amet');
insert into livro (autor, data_publicacao, preco, titulo) values ('Bailie Doubrava', '2003-04-10', '141.10', 'ridiculus mus vivamus vestibulum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Sibyl O''Roan', '1974-09-30', '133.63', 'pellentesque volutpat dui maecenas tristique est et');
insert into livro (autor, data_publicacao, preco, titulo) values ('Frankie Thirtle', '2014-08-19', '138.90', 'nulla quisque arcu libero rutrum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Cecily Kleingrub', '1962-07-22', '65.71', 'odio elementum eu interdum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Galen McLean', '2003-01-13', '89.22', 'aliquet ultrices erat tortor sollicitudin');
insert into livro (autor, data_publicacao, preco, titulo) values ('Antonio Jakeman', '1965-04-20', '30.98', 'lobortis ligula sit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ronna Chasen', '1978-11-15', '160.03', 'morbi non lectus aliquam sit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Rossie Deverock', '1999-11-30', '41.16', 'venenatis tristique fusce');
insert into livro (autor, data_publicacao, preco, titulo) values ('Burty Wardrop', '1980-06-13', '174.51', 'volutpat dui maecenas tristique est et tempus semper');
insert into livro (autor, data_publicacao, preco, titulo) values ('Hayes McLafferty', '1966-06-16', '50.65', 'rhoncus sed vestibulum sit amet');
insert into livro (autor, data_publicacao, preco, titulo) values ('Elvera Greville', '1959-09-29', '150.63', 'in est risus auctor');
insert into livro (autor, data_publicacao, preco, titulo) values ('Michal Laverack', '1980-01-15', '84.76', 'aliquam lacus morbi quis tortor');
insert into livro (autor, data_publicacao, preco, titulo) values ('Stan Fearn', '2013-01-28', '166.47', 'justo etiam pretium');
insert into livro (autor, data_publicacao, preco, titulo) values ('Asia Coetzee', '2016-08-01', '123.83', 'nunc vestibulum ante ipsum');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jehu Crayke', '1973-02-24', '132.23', 'erat fermentum justo nec');
insert into livro (autor, data_publicacao, preco, titulo) values ('Skipp Weafer', '1978-08-17', '185.98', 'quis justo maecenas rhoncus aliquam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Ashely Girardengo', '1999-09-29', '122.67', 'ut massa quis augue luctus tincidunt nulla mollis');
insert into livro (autor, data_publicacao, preco, titulo) values ('Nikos Merrien', '1958-11-19', '12.50', 'tincidunt nulla mollis molestie lorem quisque ut');
insert into livro (autor, data_publicacao, preco, titulo) values ('Barbie Cranton', '1954-03-06', '199.67', 'vestibulum aliquet ultrices erat');
insert into livro (autor, data_publicacao, preco, titulo) values ('Janel Chatenet', '1963-09-22', '60.13', 'velit nec nisi vulputate nonummy maecenas tincidunt');
insert into livro (autor, data_publicacao, preco, titulo) values ('Andriana McGiven', '1990-10-22', '143.14', 'scelerisque quam turpis adipiscing lorem vitae');
insert into livro (autor, data_publicacao, preco, titulo) values ('Trixie Wellings', '1953-10-03', '76.12', 'maecenas tristique est et tempus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Eric Karlowicz', '1964-09-09', '50.15', 'sit amet erat nulla');
insert into livro (autor, data_publicacao, preco, titulo) values ('Judye Aireton', '1962-05-16', '75.75', 'morbi vel lectus in quam fringilla rhoncus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Felecia Birwhistle', '1962-10-29', '45.45', 'elementum in hac');
insert into livro (autor, data_publicacao, preco, titulo) values ('Britteny Shackelton', '1988-02-28', '13.93', 'tincidunt eget tempus vel pede morbi');
insert into livro (autor, data_publicacao, preco, titulo) values ('Reinaldos Peart', '2016-05-22', '62.32', 'id ornare imperdiet');
insert into livro (autor, data_publicacao, preco, titulo) values ('Tris Piggen', '1977-06-27', '61.14', 'posuere cubilia curae mauris viverra diam vitae quam');
insert into livro (autor, data_publicacao, preco, titulo) values ('Sallyann Reyburn', '2018-06-16', '160.08', 'ullamcorper augue a suscipit nulla elit');
insert into livro (autor, data_publicacao, preco, titulo) values ('Marlin Kleszinski', '1982-04-15', '16.97', 'eget rutrum at lorem');
insert into livro (autor, data_publicacao, preco, titulo) values ('Mireielle Dayment', '1971-01-10', '93.08', 'accumsan tortor quis turpis sed ante vivamus tortor');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lutero Sneyd', '1986-10-06', '198.24', 'curae nulla dapibus dolor vel est donec odio');
insert into livro (autor, data_publicacao, preco, titulo) values ('Sax Stockton', '1966-04-13', '105.30', 'donec diam neque vestibulum eget vulputate');
insert into livro (autor, data_publicacao, preco, titulo) values ('Gwendolin Goutcher', '1956-09-21', '97.73', 'convallis duis consequat dui');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lavina Hannan', '1985-07-21', '60.33', 'vulputate elementum nullam varius');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jerome Mate', '1962-07-10', '40.77', 'amet consectetuer adipiscing elit proin risus praesent lectus');
insert into livro (autor, data_publicacao, preco, titulo) values ('Jackquelin Bernardt', '1986-11-21', '136.39', 'non pretium quis lectus suspendisse potenti in');
insert into livro (autor, data_publicacao, preco, titulo) values ('Lucita McCormack', '2000-08-09', '15.56', 'magna at nunc commodo placerat praesent');
